
import "./globals.css";
import type { Metadata } from "next";
import { Big_Shoulders_Display, Inter,JetBrains_Mono } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import ActiveSectionContextProvider from "@/context/activeSectionContextProvider";


const Big_Shoulders = Big_Shoulders_Display({ subsets: ["latin"] });
const JetBrains = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-jetbrains",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${Big_Shoulders.className} ${JetBrains.variable} dark:before:bg-none`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ActiveSectionContextProvider>
            {children}
          </ActiveSectionContextProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
